const IO_CONNECT = 'connect'
const IO_DISCONNECT = 'disconnect'
const IO_CLIENT_HELLO = 'IO_CLIENT_HELLO'
const IO_CLIENT_JOIN_ROOM = 'IO_CLIENT_JOIN_ROOM'
const IO_SERVER_HELLO = 'IO_SERVER_HELLO'

module.exports = {
    IO_CONNECT,IO_DISCONNECT,IO_CLIENT_HELLO,IO_CLIENT_JOIN_ROOM,IO_SERVER_HELLO
}